### ISSUE TITLE
No results found on some laptops

### ISSUE THREAD

**Issue by longboarder241** [pystardust/ani-cli#1027]
So I have ani-cli installed on two laptops, one running artix that seems to have no issues whatsoever and another running void linux and has an 32 bit processor.  I usually use that 32 bit laptop on the go since it has a small form factor.  Anyways Yesterday I was able to stream initial d fine through it on the 32 bit system except an issue where next would repeat the last episode when clicking next but today I'm facing a bigger issue where every searchand result gives "no results found".  I pinged my network too to make sure its working fine

**Comment by longboarder241** [comment]
and its completely okay.  I'm even messaging this issue through suckless surf as we speak.  Again any help would be great

**Comment by Derisis13** [comment]
Wasn't this the same time as #1025?

**Comment by RaynardGerraldo** [comment]
> So I have ani-cli installed on two laptops, one running artix that seems to have no issues whatsoever and another running void linux and has an 32 bit processor. I usually use that 32 bit laptop on the go since it has a small form factor. Anyways Yesterday I was able to stream initial d fine through it on the 32 bit system except an issue where next would repeat the last episode when clicking next but today I'm facing a bigger issue where every searchand result gives "no results found". I pinged my network too to make sure its working fine

can you update the script and try again? "except an issue where next would repeat the last episode" this is solved , 2nd issue is not clear yet, most likely had something to do with #1025

**Comment by longboarder241** [comment]
I'll give it a shot

**Comment by ruvasqm** [comment]
I'm having this exact issue
## System
OS: Ubuntu jammy amd64
shell: zsh

## Steps:

- run `ani-cli healer`

## Expected:

Dont make me say what I expected

## Actual:

Two other series

---

I'm getting every other result I search for I think, if the actual site is __allanime.site__ then it should get the result I was looking for. Looking through the script I saw there were other sites, maybe they're kinda interfering or something? Maybe the site that actually has the series is down.

**Comment by port19x** [comment]
I'll be linking this to #1037

Reopen if the 4.1 release doesn't fix things
