### ISSUE TITLE
MPV player won't launch

### ISSUE THREAD

**Issue by ttx99** [pystardust/ani-cli#1181]
**Metadata (please complete the following information)**
Version: 4.5
OS: Windows 10 
Shell: git bash
Anime: record of ragnarok

**Describe the bug**
MPV player wont launch
**Steps To Reproduce**

1. Run `ani-cli record of ragnarok`
2. Choose 1
3. Choose episode 1

**Expected behavior**
mpv should launch
![1](https://github.com/pystardust/ani-cli/assets/95531944/83a11419-f5b1-46af-8a83-bd0de795170a)
![2](https://github.com/pystardust/ani-cli/assets/95531944/72912abc-adbc-49ba-a46f-97802245f51e)

**Additional context**

**Comment by port19x** [comment]
Can't reproduce on linux. 
Could this be due to installation mistakes?
Did you install ani-cli manually or via scoop?

**Comment by ttx99** [comment]
from source

**Comment by IgorFreik** [comment]
same for me on macOS Monterey 12.5.1

**Comment by port19x** [comment]
> same for me on macOS Monterey 12.5.1
> 
> <img alt="Screen Shot 2023-07-30 at 20 09 04" width="576" src="https://user-images.githubusercontent.com/87539984/257068152-f7006165-caa2-4e78-85d4-397b4da99f25.png">

That was actually due to a mktemp bug I introduced in 4.5.2, I merged the fix an hour ago.

**Comment by port19x** [comment]
> from source

So this is a bit tough to troubleshoot.
The problem basically boils down to mpv somehow not being present in your PATH.
ani-cli does seem do work fine from the screenshots provided by you, it just fails to open the player.
This indicates that our installation instructions for windows from source are incomplete.

If the scoop installation is an option for you, that one should work and is the preferred method.

**Comment by ttx99** [comment]
![1](https://github.com/pystardust/ani-cli/assets/95531944/2e80ba8d-3850-4c40-8cb7-b8f112eef2e9)
![2](https://github.com/pystardust/ani-cli/assets/95531944/5247c72e-9b78-48e5-8ad8-d39ec3d021c0)

still wont launch

**Comment by port19x** [comment]
This is very odd

**Comment by justchokingaround** [comment]
ani-cli uses the `mpv.exe` executable not `mpv`, check `which mpv.exe` and also it would be nice if we could get some logs please
```sh
sh -x $(which ani-cli) naruto -N -e 1 &>ani-cli.log
```
then send ani-cli.log here pls

**Comment by ShanChar** [comment]
A bit weird posting it here but, why do I keep getting this??
```
Checking dependencies...
No results found!
```

**Comment by ttx99** [comment]
![1](https://github.com/pystardust/ani-cli/assets/95531944/f4621c16-f011-4707-89c5-03fc7798c81b)
![2](https://github.com/pystardust/ani-cli/assets/95531944/ed30c15b-780f-42d3-94d4-e9beaa903b76)

**Comment by justchokingaround** [comment]
@ttx99 
can you try this out, and let me know if it fixes the bug?
```sh
sh <(curl -s https://raw.githubusercontent.com/pystardust/ani-cli/windows-bug/ani-cli) naruto -N -e 1
```

**Comment by ttx99** [comment]
it just exits 
![1](https://github.com/pystardust/ani-cli/assets/95531944/a1e81c49-ed54-40a4-aad7-69f315b7d21d)

**Comment by justchokingaround** [comment]
what does the log look like?

just add `-x &>ani-cli.log` to the previous command

**Comment by ttx99** [comment]
![1](https://github.com/pystardust/ani-cli/assets/95531944/9dd22fc7-18c4-4dff-8deb-ee9778b0112b)
[ani-cli.log](https://github.com/pystardust/ani-cli/files/12269913/ani-cli.log)

**Comment by justchokingaround** [comment]
my bad, remove the `-x` at the end and put it directly after the `sh` at the start, sorry about that

**Comment by ttx99** [comment]
it just exits
[ani-cli.log](https://github.com/pystardust/ani-cli/files/12269928/ani-cli.log)

**Comment by justchokingaround** [comment]
does the following command work?
```sh
mpv '--force-media-title=Boruto Naruto Next Generations Episode 1' https://video.wixstatic.com/video/e441d9_ee77f7165b384f07a5552b7496e8cc3f/1080p/mp4/file.mp4
```

**Comment by ttx99** [comment]
yes,
![1](https://github.com/pystardust/ani-cli/assets/95531944/3093904a-ab5a-4f65-bb87-01cdf166f4a4)

**Comment by justchokingaround** [comment]
and with `mpv.exe` ?

**Comment by ttx99** [comment]
i dont know what you mean exactly but that command launches mpv
![1](https://github.com/pystardust/ani-cli/assets/95531944/45df7b33-3456-4917-9dc6-337ee07f90c8)

**Comment by justchokingaround** [comment]
i mean 
```sh
mpv.exe '--force-media-title=Boruto Naruto Next Generations Episode 1' https://video.wixstatic.com/video/e441d9_ee77f7165b384f07a5552b7496e8cc3f/1080p/mp4/file.mp4
```

**Comment by ttx99** [comment]
it doesnt work 
![1](https://github.com/pystardust/ani-cli/assets/95531944/a11d8b4a-0955-47ff-b60c-87b07de50fcb)

**Comment by port19x** [comment]
> A bit weird posting it here but, why do I keep getting this??
> 
> ```
> Checking dependencies...
> No results found!
> ```

Update ani-cli. If it still doesn't work, open a separate issue

**Comment by ttx99** [comment]
fixed thx
![Uploading 1.png…]()
